### ISSUE TITLE
USAFacts should group by geo before smoothing

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#707] opened 2021-01-19 15:50 UTC
USAFacts smoothing just jams the whole data series in there without regard for geo_id:

https://github.com/cmu-delphi/covidcast-indicators/blob/e8035936647065e8b082b75a76d39046e99d7f81/usafacts/delphi_usafacts/run.py#L100-L101

& has been that way since November: https://github.com/cmu-delphi/covidcast-indicators/pull/429/files

The equivalent operation in JHU groups by what I'm assuming is geo_id first before applying the smoother in a transform operation:

https://github.com/cmu-delphi/covidcast-indicators/blob/e8035936647065e8b082b75a76d39046e99d7f81/jhu/delphi_jhu/run.py#L106

The grouping implementation is correct.

**Comment by chinandrew** [comment] 2021-01-19 20:51
Alrighty, this was a fun one to hunt down. So the issue is real, and will lead to things like the following:

_raw df, computing cumulative counts 7dav_
```
     geo_id  timestamp  population  new_counts  cumulative_counts  incidence  cumulative_prop
1082  01003 2021-01-12    223234.0       155.0            15572.0  69.433868      6975.639911
1083  01003 2021-01-13    223234.0       129.0            15701.0  57.786896      7033.426808
1084  01003 2021-01-14    223234.0       140.0            15841.0  62.714461      7096.141269
1085  01003 2021-01-15    223234.0       161.0            16002.0  72.121630      7168.262899
1086  01003 2021-01-16    223234.0       174.0            16176.0  77.945116      7246.208015
1087  01003 2021-01-17    223234.0        75.0            16251.0  33.597033      7279.805048
1088  01003 2021-01-18    223234.0        95.0            16346.0  42.556241      7322.361289
1089  01005 2020-01-22     24686.0         0.0                0.0   0.000000         0.000000
1090  01005 2020-01-23     24686.0         0.0                0.0   0.000000         0.000000
1091  01005 2020-01-24     24686.0         0.0                0.0   0.000000         0.000000
1092  01005 2020-01-25     24686.0         0.0                0.0   0.000000         0.000000
1093  01005 2020-01-26     24686.0         0.0                0.0   0.000000         0.000000
1094  01005 2020-01-27     24686.0         0.0                0.0   0.000000         0.000000
1095  01005 2020-01-28     24686.0         0.0                0.0   0.000000         0.000000
```
_smoothed df, note the values extending into `01005`_
```
     geo_id  timestamp  population  new_counts  cumulative_counts  incidence  cumulative_prop           val
1082  01003 2021-01-12    223234.0       155.0            15572.0  69.433868      6975.639911  15153.000000
1083  01003 2021-01-13    223234.0       129.0            15701.0  57.786896      7033.426808  15302.285714
1084  01003 2021-01-14    223234.0       140.0            15841.0  62.714461      7096.141269  15444.571429
1085  01003 2021-01-15    223234.0       161.0            16002.0  72.121630      7168.262899  15580.285714
1086  01003 2021-01-16    223234.0       174.0            16176.0  77.945116      7246.208015  15719.428571
1087  01003 2021-01-17    223234.0        75.0            16251.0  33.597033      7279.805048  15851.428571
1088  01003 2021-01-18    223234.0        95.0            16346.0  42.556241      7322.361289  15984.142857
1089  01005 2020-01-22     24686.0         0.0                0.0   0.000000         0.000000  13759.571429
1090  01005 2020-01-23     24686.0         0.0                0.0   0.000000         0.000000  11516.571429
1091  01005 2020-01-24     24686.0         0.0                0.0   0.000000         0.000000   9253.571429
1092  01005 2020-01-25     24686.0         0.0                0.0   0.000000         0.000000   6967.571429
1093  01005 2020-01-26     24686.0         0.0                0.0   0.000000         0.000000   4656.714286
1094  01005 2020-01-27     24686.0         0.0                0.0   0.000000         0.000000   2335.142857
1095  01005 2020-01-28     24686.0         0.0                0.0   0.000000         0.000000      0.000000
```

This means that the first 6 days of each geography (except the very first one) will be using values from the preceding geography, leading to the wrong counts. 

However, this issue never made it to the API since the data begins on 2020-1-22, and the indicator is set to start exporting 7dav signals on 2020-2-1, meaning the erroneous values from 1-22 to 1-27 never see the light of day. 

Got lucky on this one, and a permanent fix for this bug is in #708

**Closed** 2021-01-19 21:27 UTC
Labels: bug
