### ISSUE TITLE
New Google Symptoms indicator

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#270] opened 2020-09-11 14:13 UTC
Google has released a new search trends product. We should create an indicator for it, and swap out the existing GHT indicator. The new product is substantially more complex, and will require some modeling & analysis work before we are ready to actually write the indicator. 

Notes from @huisaddison on his presentation to Modeling on 10 September:

> • Discussion outline: https://github.com/cmu-delphi/covidcast-modeling/blob/master/google_symptoms_exploration/plans.md
> • Notebooks with initial EDA and the a correlations analysis: https://github.com/cmu-delphi/covidcast-modeling/tree/master/google_symptoms_exploration
> • Use these notebooks to jumpstart future correlations analysis (my helper functions allow data to be downloaded / cached and then turned into a COVIDCAST-style dataframe)
> Open projects (also in the DAP Google Doc):
> • Google Symptoms: Comprehensive correlations analysis for new Google Symptoms data: (“Open problems”: https://github.com/cmu-delphi/covidcast-modeling/blob/master/google_symptoms_exploration/plans.md)
> • Google Symptoms: Clinically guided approach to creating a new COVID signal from Google Symptoms data: (“Two approaches”, bullet 1: https://github.com/cmu-delphi/covidcast-modeling/blob/master/google_symptoms_exploration/plans.md) combined with clinical data, e.g., Nigam’s Stanford data: https://docs.google.com/spreadsheets/d/1iZZvbv94fpZdC6XaiPosiniMOh18etSPliAXVlLLr1w/edit#gid=344371264
> • Google Symptoms: Supervised learning approach to creating a new COVID signal from Google Symptoms data: (“Two approaches”, bullet 2: https://github.com/cmu-delphi/covidcast-modeling/blob/master/google_symptoms_exploration/plans.md)

**Comment by krivard** [comment] 2020-10-07 19:12
Possible missingness problem discrepancy between GHT and GS is resolved: high GHT areas that were missing in GS turn out to be places with very low sample size, indicating that the high GHT value is both spurious and should be filtered out anyway.

More details in #covid-19-ght.

**Comment by nmdefries** [comment] 2020-10-07 20:37
Detail on missingness investigation results [here](https://delphi-org.slack.com/archives/C011KAR4DN2/p1602089419022100).

**Comment by krivard** [comment] 2020-10-14 19:23
GS improves predictions more than both GHT and GHT+GS, which is pretty excellent.

Still todo:
- [ ] Should we include more search topics? Currently a straight duplicate

**Comment by nmdefries** [comment] 2020-10-17 16:52
**Detail on predictive power of Google Symptoms (anosmia + ageusia)**

I used the procedures in Ryan's [symptom survey blog post](https://delphi.cmu.edu/blog/2020/09/21/can-symptoms-surveys-improve-covid-19-forecasts/) to compare predictive power of a series of simple time series models (cases only, cases + GS, cases + GHT, and cases + GS + GHT) at the state level.

Findings:

* Cases + GS outperforms all other models
* Cases + GS provides an additional 5 days of lead time in forecasting compared to the cases-only model.
* Cases + GHT adds a small amount of predictive power vs cases-only model
* But cases + GS + GHT is not better than cases + GS
* [Model evaluation plots](https://github.com/cmu-delphi/covidcast-modeling/blob/77f36d380ba68d346f325567689af6dd92fa5830/google_symptoms_exploration/03_compare_gs_ght.html)

Next steps:

* Put into production dupe of GHT indicator using GS anosmia + ageusia terms only
* Investigate which additional search terms to include in GS indicator. Repeat model analysis.

**Comment by huisaddison** [comment] 2020-11-03 23:31
#344 appears to be ready.  What is the timeline for release?  I would like to include Google Symptoms in https://github.com/cmu-delphi/covidcast-modeling/issues/18 .  Thanks!

**Closed** 2020-11-05 14:53 UTC
Labels: API addition, modeling

**Comment by krivard** [comment] 2020-11-05 15:01
@huisaddison ostensibly we could include it in 1.11 that will go out this month; I've drawn up a release ticket #438  to track the remaining effort.
