### ISSUE TITLE
add issue_date as a part of the export directory for regular runs

### ISSUE THREAD

**Issue by aysim319** [cmu-delphi/covidcast-indicators#2008] opened 2024-07-30 15:29 UTC
**Actual Behavior:**
After a regular run for indicator is successful, but acquisition fails for some reason, unless a manual patch is done, the issue date for that specific run is set to the date when the acquisition is successfully run. Therefore, there might be a one off for the issue date for the data.

**Expected behavior**
When acquisition picks up the output from indicators there should be a date associated with the run so that regardless of acquisition run being delayed, there should an issue date that the acquisition pick up and assign the correct issue date

**Comment by melange396** [comment] 2024-07-30 15:32
duplicate of #1907

**Closed by melange396** 2024-07-30 15:32 UTC
Labels: data quality
